compilers:
  - compiler:
      spec: gcc@10
      paths:
        cc: /usr/bin/gcc-10
        cxx: /usr/bin/g++-10
        f77: /usr/bin/gfortran-10
        fc: /usr/bin/gfortran-10
      flags: {}
      operating_system: ubuntu20.04
      target: any
      modules:
      - gcc/10
      environment:
        prepend_path:
          PATH: '/usr/bin'
          LD_LIBRARY_PATH: '/usr/lib64'
          CPATH: '/usr/include'
      extra_rpaths: []
