packages:
  all:
    compiler:: [gcc@9.3]
    providers:
      mpi:: [openmpi@4.0.3]

### MPI, Python, MKL
  mpi:
    buildable: False
  openmpi:
    externals:
    - spec: openmpi@4.0.3
      prefix: /usr
      modules:
      - openmpi/4.0.3
  python:
    buildable: False
    externals:
    - spec: python@3.8.10
      prefix: /home/builder/miniconda-4.12.0
      modules:
      - miniconda/3.8.10

### All other external packages listed alphabetically
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
  bash:
    externals:
    - spec: bash@5.0.17
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.8
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.22.5
      prefix: /usr/local
      modules:
      - cmake/3.22.5
  curl:
    externals:
    - spec: curl@7.68.0+gssapi+ldap+nghttp2
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7
      prefix: /usr
  file:
    externals:
    - spec: file@5.11
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.7.0
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.5.37+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.0.2
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.07
      prefix: /usr
  git:
    externals:
    - spec: git@2.28.0+tcltk
      prefix: /apps/git-2.28.0
    - spec: git@1.8.3.1~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@2.12.0
      prefix: /apps/git-2.28.0
  gmake:
    externals:
    - spec: gmake@3.82
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.2
      prefix: /usr
  openjdk:
    externals:
    - spec: openjdk@1.8.0_222-b10
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.15.1
      prefix: /usr
  libfuse:
    externals:
    - spec: libfuse@2.9.2
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
  lustre:
    externals:
    - spec: lustre@2.12.6_ddn51
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@5.9.20130511+termlib abi=5
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@7.4p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.0.2k-fips
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.16.3+cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr
  qt:
    externals:
    - spec: qt@5.9.2
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.1.2
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.2.2
      prefix: /usr
  sqlite:
    externals:
    - spec: sqlite@3.7.17~fts~functions+rtree
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.26
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@5.1
      prefix: /usr
  texlive:
    externals:
    - spec: texlive@20130530
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.20.3
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.4
      prefix: /usr
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
