spack:
  config:
    install_tree:
      root: $env/install
    deprecated: true
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
        tcl: $env/install/modulefiles
      lmod:
        projections:
          parallelio: 'pio/{version}'
      tcl: 
        projections:
          parallelio: '{^mpi.name}/{^mpi.version}/{compiler.name}/{compiler.version}/pio/{version}'

  include: []

  concretizer:
    unify: true

  specs:
  - jasper@2.0.25
  - zlib@1.2.11
  - libpng@1.6.37
  - hdf5@1.10.6
  - netcdf-c@4.7.4
 
  
