spack:
  config:
    install_tree:
      root: $env/install
    deprecated: true
  modules:
    default:
      roots:
        lmod: $env/install/modulefiles
        tcl: $env/install/modulefiles
      lmod:
        projections:
          parallelio: 'pio/{version}'
      tcl: 
        projections:
          parallelio: '{^mpi.name}/{^mpi.version}/{compiler.name}/{compiler.version}/pio/{version}'

  include: []

  concretizer:
    unify: when_possible

  specs:
  - mapl@2.22.0
  - bufr@11.7.0
 
  
